### ISSUE TITLE
1.3.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [michaelrsweet/pappl#254] opened 2023-02-17 04:32 UTC
**Describe the bug**
Looks like test suite is failing

**To Reproduce**
- setup source tree with
```spec
%configure \
        --disable-debug \
        --disable-static \
        --with-tls=openssl \
```
- `make`
- `make test`

**Expected behavior**
Test suite should not fail.

**Screenshots**
```console
+ cd pappl-1.3.1
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
Testing in doc...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/doc'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/doc'
Testing in man...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/man'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/man'
Testing in pappl...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/pappl'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/pappl'
Testing in testsuite...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/testsuite'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/testsuite'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/testsuite'
Good Basic GET: : PASS
No Content Length Response: : PASS
Bad Basic GET: : PASS
Basic HEAD: : PASS
Basic POST: : PASS
POST Expect w/Continue: : PASS
POST Expect w/o Continue: : PASS
Good Chunked GET: : PASS
Chunked POST: : PASS
Bad Chunked GET: : PASS
make[1]: *** [Makefile:53: test] Error 134
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.1/testsuite'
make: *** [Makefile:67: test] Error 1
```

**System Information:**
 - OS: Linux x86/64
 - Browser: N/A
 - Version: 1.3.1
 
**Additional context**
I'm not sure what more I shoud provide.Please let me know if you need more details.

**Comment by michaelrsweet** [comment] 2023-03-07 13:02
I am unable to reproduce this on my systems/VMs. "Error 134" probably means "crashed on signal 6" which is SIGABRT. Without a core dump + backtrace it may be impossible to know what it causing the problem.

**Comment by michaelrsweet** [comment] 2023-05-06 12:59
Closing for lack of information/unable to reproduce.

**Closed by michaelrsweet** 2023-05-06 12:59 UTC
Labels: investigating

**Comment by kloczek** [comment] 2023-05-06 18:09
Just retested new 1.3.2 and now test suite is faine
```console
+ cd pappl-1.3.2
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
Testing in doc...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/doc'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/doc'
Testing in man...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/man'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/man'
Testing in pappl...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/pappl'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/pappl'
Testing in testsuite...
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/testsuite'
make[1]: warning: -j48 forced in submake: resetting jobserver mode.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/testsuite'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/testsuite'
Good Basic GET: : PASS
No Content Length Response: : PASS
Bad Basic GET: : PASS
Basic HEAD: : PASS
Basic POST: : PASS
POST Expect w/Continue: : PASS
POST Expect w/o Continue: : PASS
Good Chunked GET: : PASS
Chunked POST: : PASS
Bad Chunked GET: : PASS
Starting tests...
api: papplSystemFindLoc('de'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got 'Ein Drucker mit diesem Namen existiert bereits.')
api: papplSystemFindLoc('en'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got 'A printer with that name already exists.')
api: papplSystemFindLoc('es'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got 'Una impresora con ese nombre ya existe.')
api: papplSystemFindLoc('fr'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got 'Une imprimante avec ce nom existe déjà.')
api: papplSystemFindLoc('it'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got 'Una stampante con quel nome esiste già.')
api: papplSystemFindLoc('ja'): PASS
api: papplLocGetString('A printer with that name already exists.'): PASS (got '既に存在している名前のプリンター。')
api: papplSystemFindLoc('zz'): PASS (got NULL)
api: papplLocGetString('A printer with that name already exists.'): PASS (got key string)
api: papplSystemGetAdminGroup: PASS
api: papplSystemGet/SetAdminGroup('admin-0'): PASS
api: papplSystemGet/SetAdminGroup('admin-1'): PASS
api: papplSystemGet/SetAdminGroup('admin-2'): PASS
api: papplSystemGet/SetAdminGroup('admin-3'): PASS
api: papplSystemGet/SetAdminGroup('admin-4'): PASS
api: papplSystemGet/SetAdminGroup('admin-5'): PASS
api: papplSystemGet/SetAdminGroup('admin-6'): PASS
api: papplSystemGet/SetAdminGroup('admin-7'): PASS
api: papplSystemGet/SetAdminGroup('admin-8'): PASS
api: papplSystemGet/SetAdminGroup('admin-9'): PASS
api: papplSystemGet/SetAdminGroup(NULL): PASS
api: papplSystemGetContact: PASS
api: papplSystemGet/SetContact('Admin 0'): PASS
api: papplSystemGet/SetContact('Admin 1'): PASS
api: papplSystemGet/SetContact('Admin 2'): PASS
api: papplSystemGet/SetContact('Admin 3'): PASS
api: papplSystemGet/SetContact('Admin 4'): PASS
api: papplSystemGet/SetContact('Admin 5'): PASS
api: papplSystemGet/SetContact('Admin 6'): PASS
api: papplSystemGet/SetContact('Admin 7'): PASS
api: papplSystemGet/SetContact('Admin 8'): PASS
api: papplSystemGet/SetContact('Admin 9'): PASS
api: papplSystemGetDefaultPrinterID: PASS (1)
api: papplSystemSetDefaultPrinterID(2): PASS
api: papplSystemSetDefaultPrinterID(1): PASS
api: papplSystemGetDefaultPrintGroup: PASS
api: papplSystemGet/SetDefaultPrintGroup('users-0'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-1'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-2'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-3'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-4'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-5'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-6'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-7'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-8'): PASS
api: papplSystemGet/SetDefaultPrintGroup('users-9'): PASS
api: papplSystemGet/SetDefaultPrintGroup(NULL): PASS
api: papplSystemGetDNSSDName: PASS
api: papplSystemGet/SetDNSSDName('System Test A'): PASS
api: papplSystemGet/SetDNSSDName('System Test B'): PASS
api: papplSystemGet/SetDNSSDName('System Test C'): PASS
api: papplSystemGet/SetDNSSDName('System Test D'): PASS
api: papplSystemGet/SetDNSSDName('System Test E'): PASS
api: papplSystemGet/SetDNSSDName('System Test F'): PASS
api: papplSystemGet/SetDNSSDName('System Test G'): PASS
api: papplSystemGet/SetDNSSDName('System Test H'): PASS
api: papplSystemGet/SetDNSSDName('System Test I'): PASS
api: papplSystemGet/SetDNSSDName('System Test J'): PASS
api: papplSystemGet/SetDNSSDName(NULL): PASS
api: papplSystemGetFooterHTML: PASS
api: papplSystemSetFooterHTML('Mike wuz here.'): PASS
api: papplSystemGetGeoLocation: PASS
api: papplSystemGet/SetGeoLocation('bad-value'): PASS
api: papplSystemGet/SetGeoLocation('geo:29.979175,31.134358'): PASS
api: papplSystemGet/SetGeoLocation('geo:37.949722,27.363889'): PASS
api: papplSystemGet/SetGeoLocation('geo:37.637861,21.63'): PASS
api: papplSystemGet/SetGeoLocation('geo:36.451111,28.227778'): PASS
api: papplSystemGet/SetGeoLocation('geo:31.213889,29.885556'): PASS
api: papplSystemGet/SetGeoLocation('geo:43.0828201,-79.0763516'): PASS
api: papplSystemGet/SetGeoLocation('geo:36.0545936,-112.2307085'): PASS
api: papplSystemGet/SetGeoLocation('geo:-22.9691208,-43.2583044'): PASS
api: papplSystemGet/SetGeoLocation('geo:-16.7546653,143.8322946'): PASS
api: papplSystemGet/SetGeoLocation('geo:46.4707,-80.9961'): PASS
api: papplSystemGet/SetGeoLocation(NULL): PASS
api: papplSystemGetHostname: PASS
api: papplSystemGet/SetHostname('example0.org'): PASS
api: papplSystemGet/SetHostname('example1.org'): PASS
api: papplSystemGet/SetHostname('example2.org'): PASS
api: papplSystemGet/SetHostname('example3.org'): PASS
api: papplSystemGet/SetHostname('example4.org'): PASS
api: papplSystemGet/SetHostname('example5.org'): PASS
api: papplSystemGet/SetHostname('example6.org'): PASS
api: papplSystemGet/SetHostname('example7.org'): PASS
api: papplSystemGet/SetHostname('example8.org'): PASS
api: papplSystemGet/SetHostname('example9.org'): PASS
api: papplSystemGet/SetHostName(NULL): PASS
api: papplSystemGetLocation: PASS
api: papplSystemGet/SetLocation('Great Pyramid of Giza'): PASS
api: papplSystemGet/SetLocation('Temple of Artemis at Ephesus'): PASS
api: papplSystemGet/SetLocation('Statue of Zeus at Olympia'): PASS
api: papplSystemGet/SetLocation('Colossus of Rhodes'): PASS
api: papplSystemGet/SetLocation('Lighthouse of Alexandria'): PASS
api: papplSystemGet/SetLocation('Niagara Falls'): PASS
api: papplSystemGet/SetLocation('Grand Canyon'): PASS
api: papplSystemGet/SetLocation('Christ the Redeemer'): PASS
api: papplSystemGet/SetLocation('Great Barrier Reef'): PASS
api: papplSystemGet/SetLocation('Science North'): PASS
api: papplSystemGet/SetLocation(NULL): PASS
api: papplSystemGetLogLevel: PASS
api: papplSystemSetLogLevel(PAPPL_LOGLEVEL_FATAL): PASS
api: papplSystemSetLogLevel(PAPPL_LOGLEVEL_ERROR): PASS
api: papplSystemSetLogLevel(PAPPL_LOGLEVEL_WARN): PASS
api: papplSystemSetLogLevel(PAPPL_LOGLEVEL_INFO): PASS
api: papplSystemSetLogLevel(PAPPL_LOGLEVEL_DEBUG): PASS
api: papplSystemGetMaxLogSize: PASS
api: papplSystemSetMaxLogSize(0): PASS
api: papplSystemSetMaxLogSize(1048576): PASS
api: papplSystemSetMaxLogSize(2097152): PASS
api: papplSystemSetMaxLogSize(3145728): PASS
api: papplSystemSetMaxLogSize(4194304): PASS
api: papplSystemSetMaxLogSize(5242880): PASS
api: papplSystemSetMaxLogSize(6291456): PASS
api: papplSystemSetMaxLogSize(7340032): PASS
api: papplSystemSetMaxLogSize(8388608): PASS
api: papplSystemSetMaxLogSize(9437184): PASS
api: papplSystemSetMaxLogSize(10485760): PASS
api: papplSystemSetMaxLogSize(11534336): PASS
api: papplSystemSetMaxLogSize(12582912): PASS
api: papplSystemSetMaxLogSize(13631488): PASS
api: papplSystemSetMaxLogSize(14680064): PASS
api: papplSystemSetMaxLogSize(15728640): PASS
api: papplSystemSetMaxLogSize(16777216): PASS
api: papplSystemSetMaxLogSize(0): PASS
api: papplSystemGetNextPrinterID: PASS
api: papplSystemSetNextPrinterID(319439): PASS
api: papplSystemGetOrganization: PASS
api: papplSystemGet/SetOrganization('Organization A'): PASS
api: papplSystemGet/SetOrganization('Organization B'): PASS
api: papplSystemGet/SetOrganization('Organization C'): PASS
api: papplSystemGet/SetOrganization('Organization D'): PASS
api: papplSystemGet/SetOrganization('Organization E'): PASS
api: papplSystemGet/SetOrganization('Organization F'): PASS
api: papplSystemGet/SetOrganization('Organization G'): PASS
api: papplSystemGet/SetOrganization('Organization H'): PASS
api: papplSystemGet/SetOrganization('Organization I'): PASS
api: papplSystemGet/SetOrganization('Organization J'): PASS
api: papplSystemGet/SetOrganization(NULL): PASS
api: papplSystemGetOrganizationalUnit: PASS
api: papplSystemGet/SetOrganizationalUnit('A Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('B Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('C Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('D Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('E Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('F Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('G Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('H Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('I Team'): PASS
api: papplSystemGet/SetOrganizationalUnit('J Team'): PASS
api: papplSystemGet/SetOrganizationalUnit(NULL): PASS
api: papplSystemGetUUID: PASS
api: papplSystemGet/SetUUID('urn:uuid:9e0d1864-ee67-db72-df58-a9bc2a90988a'): PASS
api: papplSystemGet/SetUUID('urn:uuid:dd624423-4fe3-9369-7aa5-c7cce00f4af0'): PASS
api: papplSystemGet/SetUUID('urn:uuid:79a4946d-8097-6edf-4624-c58b078bcbbf'): PASS
api: papplSystemGet/SetUUID('urn:uuid:1bd85271-07bb-de1c-4c33-25b619540b33'): PASS
api: papplSystemGet/SetUUID('urn:uuid:0f63768e-dde2-cf31-8525-f09ebfc8ae02'): PASS
api: papplSystemGet/SetUUID('urn:uuid:5bbbdec9-34b9-3ebc-67b3-309ae5349cde'): PASS
api: papplSystemGet/SetUUID('urn:uuid:4aebbb40-499d-1bd2-3e64-435dc4edbb6a'): PASS
api: papplSystemGet/SetUUID('urn:uuid:a89901e1-090f-5e8b-ae90-0f4ba6e6ad8d'): PASS
api: papplSystemGet/SetUUID('urn:uuid:fe1698e1-4a05-8fba-1a09-40b83efcf731'): PASS
api: papplSystemGet/SetUUID('urn:uuid:fb631cae-d6eb-04a0-9d59-2a870dd1ee97'): PASS
api: papplSystemGet/SetUUID(NULL): PASS
api: papplSystemGetVersions: PASS
api: papplSystemGet/SetVersions(1): PASS
api: papplSystemGet/SetVersions(2): PASS
api: papplSystemGet/SetVersions(3): PASS
api: papplSystemGet/SetVersions(4): PASS
api: papplSystemGet/SetVersions(5): PASS
api: papplSystemGet/SetVersions(6): PASS
api: papplSystemGet/SetVersions(7): PASS
api: papplSystemGet/SetVersions(8): PASS
api: papplSystemGet/SetVersions(9): PASS
api: papplSystemGet/SetVersions(10): PASS
api: papplSystemFindPrinter(default): PASS
api: papplSystemFindPrinter(1): PASS
api: papplPrinterGetContact: PASS
api: papplPrinterGet/SetContact('Admin 0'): PASS
api: papplPrinterGet/SetContact('Admin 1'): PASS
api: papplPrinterGet/SetContact('Admin 2'): PASS
api: papplPrinterGet/SetContact('Admin 3'): PASS
api: papplPrinterGet/SetContact('Admin 4'): PASS
api: papplPrinterGet/SetContact('Admin 5'): PASS
api: papplPrinterGet/SetContact('Admin 6'): PASS
api: papplPrinterGet/SetContact('Admin 7'): PASS
api: papplPrinterGet/SetContact('Admin 8'): PASS
api: papplPrinterGet/SetContact('Admin 9'): PASS
api: papplPrinterGetPrintGroup: PASS
api: papplPrinterGet/SetPrintGroup('users-0'): PASS
api: papplPrinterGet/SetPrintGroup('users-1'): PASS
api: papplPrinterGet/SetPrintGroup('users-2'): PASS
api: papplPrinterGet/SetPrintGroup('users-3'): PASS
api: papplPrinterGet/SetPrintGroup('users-4'): PASS
api: papplPrinterGet/SetPrintGroup('users-5'): PASS
api: papplPrinterGet/SetPrintGroup('users-6'): PASS
api: papplPrinterGet/SetPrintGroup('users-7'): PASS
api: papplPrinterGet/SetPrintGroup('users-8'): PASS
api: papplPrinterGet/SetPrintGroup('users-9'): PASS
api: papplPrinterGet/SetPrintGroup(NULL): PASS
api: papplPrinterGetDNSSDName: PASS
api: papplPrinterGet/SetDNSSDName('Printer Test A'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test B'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test C'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test D'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test E'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test F'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test G'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test H'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test I'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test J'): PASS
api: papplPrinterGet/SetDNSSDName(NULL): PASS
api: papplPrinterGetGeoLocation: PASS
api: papplPrinterGet/SetGeoLocation('bad-value'): PASS
api: papplPrinterGet/SetGeoLocation('geo:29.979175,31.134358'): PASS
api: papplPrinterGet/SetGeoLocation('geo:37.949722,27.363889'): PASS
api: papplPrinterGet/SetGeoLocation('geo:37.637861,21.63'): PASS
api: papplPrinterGet/SetGeoLocation('geo:36.451111,28.227778'): PASS
api: papplPrinterGet/SetGeoLocation('geo:31.213889,29.885556'): PASS
api: papplPrinterGet/SetGeoLocation('geo:43.0828201,-79.0763516'): PASS
api: papplPrinterGet/SetGeoLocation('geo:36.0545936,-112.2307085'): PASS
api: papplPrinterGet/SetGeoLocation('geo:-22.9691208,-43.2583044'): PASS
api: papplPrinterGet/SetGeoLocation('geo:-16.7546653,143.8322946'): PASS
api: papplPrinterGet/SetGeoLocation('geo:46.4707,-80.9961'): PASS
api: papplPrinterGet/SetGeoLocation(NULL): PASS
api: papplPrinterGetLocation: PASS
api: papplPrinterGet/SetLocation('Great Pyramid of Giza'): PASS
api: papplPrinterGet/SetLocation('Temple of Artemis at Ephesus'): PASS
api: papplPrinterGet/SetLocation('Statue of Zeus at Olympia'): PASS
api: papplPrinterGet/SetLocation('Colossus of Rhodes'): PASS
api: papplPrinterGet/SetLocation('Lighthouse of Alexandria'): PASS
api: papplPrinterGet/SetLocation('Niagara Falls'): PASS
api: papplPrinterGet/SetLocation('Grand Canyon'): PASS
api: papplPrinterGet/SetLocation('Christ the Redeemer'): PASS
api: papplPrinterGet/SetLocation('Great Barrier Reef'): PASS
api: papplPrinterGet/SetLocation('Science North'): PASS
api: papplPrinterGet/SetLocation(NULL): PASS
api: papplPrinterGetNextJobID: PASS
api: papplPrinterSetNextJobID(145727): PASS
api: papplPrinterGetOrganization: PASS
api: papplPrinterGet/SetOrganization('Organization A'): PASS
api: papplPrinterGet/SetOrganization('Organization B'): PASS
api: papplPrinterGet/SetOrganization('Organization C'): PASS
api: papplPrinterGet/SetOrganization('Organization D'): PASS
api: papplPrinterGet/SetOrganization('Organization E'): PASS
api: papplPrinterGet/SetOrganization('Organization F'): PASS
api: papplPrinterGet/SetOrganization('Organization G'): PASS
api: papplPrinterGet/SetOrganization('Organization H'): PASS
api: papplPrinterGet/SetOrganization('Organization I'): PASS
api: papplPrinterGet/SetOrganization('Organization J'): PASS
api: papplPrinterGet/SetOrganization(NULL): PASS
api: papplPrinterGetOrganizationalUnit: PASS
api: papplPrinterGet/SetOrganizationalUnit('A Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('B Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('C Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('D Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('E Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('F Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('G Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('H Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('I Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('J Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit(NULL): PASS
api: papplSystemFindPrinter(2): PASS
api: papplPrinterGetContact: PASS
api: papplPrinterGet/SetContact('Admin 0'): PASS
api: papplPrinterGet/SetContact('Admin 1'): PASS
api: papplPrinterGet/SetContact('Admin 2'): PASS
api: papplPrinterGet/SetContact('Admin 3'): PASS
api: papplPrinterGet/SetContact('Admin 4'): PASS
api: papplPrinterGet/SetContact('Admin 5'): PASS
api: papplPrinterGet/SetContact('Admin 6'): PASS
api: papplPrinterGet/SetContact('Admin 7'): PASS
api: papplPrinterGet/SetContact('Admin 8'): PASS
api: papplPrinterGet/SetContact('Admin 9'): PASS
api: papplPrinterGetPrintGroup: PASS
api: papplPrinterGet/SetPrintGroup('users-0'): PASS
api: papplPrinterGet/SetPrintGroup('users-1'): PASS
api: papplPrinterGet/SetPrintGroup('users-2'): PASS
api: papplPrinterGet/SetPrintGroup('users-3'): PASS
api: papplPrinterGet/SetPrintGroup('users-4'): PASS
api: papplPrinterGet/SetPrintGroup('users-5'): PASS
api: papplPrinterGet/SetPrintGroup('users-6'): PASS
api: papplPrinterGet/SetPrintGroup('users-7'): PASS
api: papplPrinterGet/SetPrintGroup('users-8'): PASS
api: papplPrinterGet/SetPrintGroup('users-9'): PASS
api: papplPrinterGet/SetPrintGroup(NULL): PASS
api: papplPrinterGetDNSSDName: PASS
api: papplPrinterGet/SetDNSSDName('Printer Test A'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test B'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test C'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test D'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test E'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test F'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test G'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test H'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test I'): PASS
api: papplPrinterGet/SetDNSSDName('Printer Test J'): PASS
api: papplPrinterGet/SetDNSSDName(NULL): PASS
api: papplPrinterGetGeoLocation: PASS
api: papplPrinterGet/SetGeoLocation('bad-value'): PASS
api: papplPrinterGet/SetGeoLocation('geo:29.979175,31.134358'): PASS
api: papplPrinterGet/SetGeoLocation('geo:37.949722,27.363889'): PASS
api: papplPrinterGet/SetGeoLocation('geo:37.637861,21.63'): PASS
api: papplPrinterGet/SetGeoLocation('geo:36.451111,28.227778'): PASS
api: papplPrinterGet/SetGeoLocation('geo:31.213889,29.885556'): PASS
api: papplPrinterGet/SetGeoLocation('geo:43.0828201,-79.0763516'): PASS
api: papplPrinterGet/SetGeoLocation('geo:36.0545936,-112.2307085'): PASS
api: papplPrinterGet/SetGeoLocation('geo:-22.9691208,-43.2583044'): PASS
api: papplPrinterGet/SetGeoLocation('geo:-16.7546653,143.8322946'): PASS
api: papplPrinterGet/SetGeoLocation('geo:46.4707,-80.9961'): PASS
api: papplPrinterGet/SetGeoLocation(NULL): PASS
api: papplPrinterGetLocation: PASS
api: papplPrinterGet/SetLocation('Great Pyramid of Giza'): PASS
api: papplPrinterGet/SetLocation('Temple of Artemis at Ephesus'): PASS
api: papplPrinterGet/SetLocation('Statue of Zeus at Olympia'): PASS
api: papplPrinterGet/SetLocation('Colossus of Rhodes'): PASS
api: papplPrinterGet/SetLocation('Lighthouse of Alexandria'): PASS
api: papplPrinterGet/SetLocation('Niagara Falls'): PASS
api: papplPrinterGet/SetLocation('Grand Canyon'): PASS
api: papplPrinterGet/SetLocation('Christ the Redeemer'): PASS
api: papplPrinterGet/SetLocation('Great Barrier Reef'): PASS
api: papplPrinterGet/SetLocation('Science North'): PASS
api: papplPrinterGet/SetLocation(NULL): PASS
api: papplPrinterGetNextJobID: PASS
api: papplPrinterSetNextJobID(389572): PASS
api: papplPrinterGetOrganization: PASS
api: papplPrinterGet/SetOrganization('Organization A'): PASS
api: papplPrinterGet/SetOrganization('Organization B'): PASS
api: papplPrinterGet/SetOrganization('Organization C'): PASS
api: papplPrinterGet/SetOrganization('Organization D'): PASS
api: papplPrinterGet/SetOrganization('Organization E'): PASS
api: papplPrinterGet/SetOrganization('Organization F'): PASS
api: papplPrinterGet/SetOrganization('Organization G'): PASS
api: papplPrinterGet/SetOrganization('Organization H'): PASS
api: papplPrinterGet/SetOrganization('Organization I'): PASS
api: papplPrinterGet/SetOrganization('Organization J'): PASS
api: papplPrinterGet/SetOrganization(NULL): PASS
api: papplPrinterGetOrganizationalUnit: PASS
api: papplPrinterGet/SetOrganizationalUnit('A Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('B Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('C Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('D Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('E Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('F Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('G Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('H Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('I Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit('J Team'): PASS
api: papplPrinterGet/SetOrganizationalUnit(NULL): PASS
api: papplPrinterCreate(test0): PASS
api: papplPrinterDelete(test0): PASS
api: papplPrinterCreate(test0 again): PASS
api: papplPrinterCreate(test1): PASS
api: papplPrinterDelete(test1): PASS
api: papplPrinterCreate(test1 again): PASS
api: papplPrinterCreate(test2): PASS
api: papplPrinterDelete(test2): PASS
api: papplPrinterCreate(test2 again): PASS
api: papplPrinterCreate(test3): PASS
api: papplPrinterDelete(test3): PASS
api: papplPrinterCreate(test3 again): PASS
api: papplPrinterCreate(test4): PASS
api: papplPrinterDelete(test4): PASS
api: papplPrinterCreate(test4 again): PASS
api: papplPrinterCreate(test5): PASS
api: papplPrinterDelete(test5): PASS
api: papplPrinterCreate(test5 again): PASS
api: papplPrinterCreate(test6): PASS
api: papplPrinterDelete(test6): PASS
api: papplPrinterCreate(test6 again): PASS
api: papplPrinterCreate(test7): PASS
api: papplPrinterDelete(test7): PASS
api: papplPrinterCreate(test7 again): PASS
api: papplPrinterCreate(test8): PASS
api: papplPrinterDelete(test8): PASS
api: papplPrinterCreate(test8 again): PASS
api: papplPrinterCreate(test9): PASS
api: papplPrinterDelete(test9): PASS
api: papplPrinterCreate(test9 again): PASS
api: papplSystemIteratePrinters: PASS
client: Connect to server: PASS
client: Get-System-Attributes: PASS
client: Get-Printers: PASS
client: Get-Printer-Attributes=/: PASS
client: Get-Printer-Attributes=/ipp/print: PASS
client: Create-System-Subscriptions: PASS (notify-subscription-id=1)
client: Get-Subscription-Attributes: PASS
client: Make raster print file: PASS
client: Print-Job (Raster): PASS (job-id=145727)
client: Print-Job (JPEG): PASS (job-id=145728)
client: Release-Job (JPEG): PASS
client: Get-Job-Attributes (JPEG): PASS (job-state=completed)
client: Print-Job (PNG): PASS (job-id=145729)
client: Release-Job (PNG): PASS
client: Get-Job-Attributes (PNG): PASS (job-state=completed)
client: Hold-New-Jobs: PASS
client: Print-Job (Raster 2): PASS
client: Print-Job (JPEG 2): PASS (job-id=145731)
client: Print-Job (PNG 2): PASS (job-id=145732)
client: Release-Held-New-Jobs: PASS
client: Get-Notifications: PASS
client: PAPPL-Find-Devices: PASS (1 devices found)
client: PAPPL-Find-Drivers: PASS (11 drivers found)
client: PAPPL-Find-Drivers (good device-id): PASS (1 drivers found)
client: PAPPL-Find-Drivers (bad device-id): PASS (no drivers found)
client: Get-Subscription-Attributes(expiration): PASS
pwg-raster: Connect to server: PASS
pwg-raster: Get-Printer-Attributes: PASS
pwg-raster: Print-Job(auto): PASS (job-id=145733)
pwg-raster: Get-Job-Attributes(job-id=145733): PASS (job-state=9)
pwg-raster: Print-Job(auto-monochrome): PASS (job-id=145734)
pwg-raster: Get-Job-Attributes(job-id=145734): PASS (job-state=9)
pwg-raster: Print-Job(color): PASS (job-id=145735)
pwg-raster: Get-Job-Attributes(job-id=145735): PASS (job-state=9)
pwg-raster: Print-Job(monochrome): PASS (job-id=145736)
pwg-raster: Get-Job-Attributes(job-id=145736): PASS (job-state=9)
api: papplSystemSetEventCallback: PASS (count=89)
api: papplSystemAddTimerCallback: PASS (timer_count=15)

PASSED: 9 of 9 output file(s), 14.5MB
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/pappl-1.3.2/testsuite'
```
